keydb: "../keys.db"
rep_socket: "tcp://127.0.0.1:7070"
gatekeeper_socket: "tcp://127.0.0.1:7071"
knx:
    url: "ip:192.168.26.21"
    group: "1/0/80"
leds:
    heartbeat:
        pin: 18 # BCM channel, not raspi heade pin
        time: [ 0.1, 0.2, 0.1, 4.0 ] # Seconds: on-time, off-time, on-time, off-time (and loop)
    ok:
        pin: 23
        time: 2.0 # Seconds (on-time)
    error:
        pin: 24
        time: 2.0
log:
    file: "/tmp/nfc_lock_access.log"
